env:
    - BAZEL_VERSION='0.4.2' BAZEL_SHA256='b76b62a8c0eead1fc2215699382f1608c7bb98529fc48c5e9ef3dfa1b8b7585e'

dist: trusty

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - wget
            # Package list from http://bazel.io/docs/install.html
            - pkg-config
            - unzip
            - zip
            - zlib1g-dev

jdk:
    - oraclejdk8

before_install:
    # Local variables
    - BAZEL_FILE='bazel.sh'
    - BAZEL_CHECKSUM_FILE='bazel_checksum.txt'
    # Download Bazel installer
    - wget --quiet --output-document "${BAZEL_FILE}" "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
    # Check checksum
    - echo "${BAZEL_SHA256}  ${BAZEL_FILE}" > "${BAZEL_CHECKSUM_FILE}"
    - sha256sum --check "${BAZEL_CHECKSUM_FILE}"
    # Install Bazel
    - chmod +x "${BAZEL_FILE}"
    - ./"${BAZEL_FILE}" --user

script:
     # Sandbox is currently broken when run on travis so disable it
     # https://groups.google.com/d/msg/bazel-discuss/ddymoZ_Ed_g/Ap4LvSD-DQAJ
    - bazel build --spawn_strategy=standalone --jobs=4 //...
