env:
    - BAZEL_VERSION='0.4.2' BAZEL_SHA256='b76b62a8c0eead1fc2215699382f1608c7bb98529fc48c5e9ef3dfa1b8b7585e'

dist: trusty

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - wget
            # Package list from http://bazel.io/docs/install.html
            - pkg-config
            - unzip
            - zip
            - zlib1g-dev

jdk:
    - oraclejdk8

before_install:
    - ./travis/before_install.sh

script:
    - ./travis/bazel_build.sh
