# Copyright (c) 2016-2017 Dustin Doloff
# Licensed under Apache License v2.0

py_binary(
    name = "zip_site",
    srcs = [
        "scripts/zip_site.py",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "rename_zip_paths",
    srcs = [
        "scripts/rename_zip_paths.py",
    ],
    visibility = ["//visibility:public"],
)
