# Copyright (c) 2016 Dustin Doloff
# Licensed under Apache License v2.0

py_binary(
    name = "generate_variables",
    srcs = [
        "scripts/generate_variables.py",
    ],
    visibility = [ "//visibility:public" ],
)
