# Copyright (c) 2016 Dustin Doloff
# Licensed under Apache License v2.0

py_binary(
    name = "minify_ttx",
    srcs = [
        "scripts/minify_ttx.py",
    ],
    visibility = ["//visibility:public"],
)
